### ISSUE TITLE
Crash on line 69 of FearTheSun.lua

### ISSUE THREAD

**Issue by MrHrulgin** [crispiboi/FearTheSun#1]
Hiya, I got a crash in 41.44 that seems to be originating from your mod? I was fleeing March Ridge and it crashed when I was about [here](https://map.projectzomboid.com/#0.40113154165142545,0.3540438541519193,90.14057714429322).

I believe this is the relevant portion of the log. I did have other mods enabled, but nothing that modified zombie behavior.

STACK TRACE
-----------------------------------------
function: lureZombiesInsideTwo -- file: FearTheSun.lua line # 69.
[17-10-20 21:56:46.230] ERROR: General, 1602997006230> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: getX of non-table: null at KahluaThread.tableget line:1690..
[17-10-20 21:56:46.230] ERROR: General, 1602997006230> DebugLogStream.printException> Stack trace:.
[17-10-20 21:56:46.232] LOG  : General, 1602997006232> -----------------------------------------
STACK TRACE
-----------------------------------------
function: lureZombiesInsideTwo -- file: FearTheSun.lua line # 69.
[17-10-20 21:56:46.232] LOG  : General, 1602997006232> .
[17-10-20 21:56:46.372] LOG  : General, 1602997006372> creating new sourcewindow: C:/Program Files (x86)/Steam/steamapps/workshop/content/108600/2182855819/mods/FearTheSun/media/lua/client/FearTheSun.lua.

**Comment by eblieb** [comment]
Same 

function: lureZombiesInsideTwo -- file: FearTheSun.lua line # 69

ERROR: General     , 1627952494099> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: getX of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1627952494099> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: getX of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:38)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:61)
	at zombie.GameTime.update(GameTime.java:536)
	at zombie.gameStates.IngameState.UpdateStuff(IngameState.java:548)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1618)
	at zombie.gameStates.IngameState.update(IngameState.java:1319)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:285)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:726)
	at zombie.GameWindow.run_ez(GameWindow.java:642)
	at zombie.GameWindow.mainThread(GameWindow.java:471)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1627952494100> -----------------------------------------
STACK TRACE
-----------------------------------------
function: lureZombiesInsideTwo -- file: FearTheSun.lua line # 69

**Comment by crispiboi** [comment]
should be resolved with 1.53
